name:                almu575
version:             0.1.0.0
github:              "dbramucci/almu575"
license:             MIT
author:              "Daniel Bramucci"
maintainer:          "dbramuccicode@gmail.com"
copyright:           "Copyright (c) 2018 Daniel Bramucci"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            The compiler for the DSL Almu575.
# category:             DSL

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ dbramucci/almu575#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2.3.0 && < 1.3
- trifecta >= 1.7.1.1 && < 1.8
- blaze-markup >= 0.8.2.1 && < 0.9
- blaze-html >= 0.9.0.1 && < 0.10
- bytestring >= 0.10.8.2 && < 0.11
- filepath >= 1.4.1.2 && < 1.5
- containers >= 0.5.10.2 && < 0.6

library:
  source-dirs: src
  dependencies:
  - text
  - trifecta
  - blaze-markup
  - blaze-html
  - bytestring
  - containers

executables:
  almu575-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - almu575
    - bytestring
    - filepath
    - trifecta

tests:
  almu575-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - almu575
